name: repl
root: /workdir

windows:
  - main:
      layout: fbde,209x50,0,0{104x50,0,0[104x25,0,0,0,104x24,0,26,3],104x50,105,0,2}
      panes:
        - node
        - fish
        - nvim /workdir/code/
