version: "3.9"
services:
  dispatcher:
    image: "nginx:1.23.4-alpine"

    depends_on:
      - webfront
      - chat-api
      - mongo-admin

    command: [nginx-debug, "-g", "daemon off;"]
    working_dir: /app
    volumes:
      - ${APPS_DIR}/dispatcher/config/templates:/etc/nginx/templates
      - ${APPS_DIR}/dispatcher/static:/usr/share/nginx/html
      - ${KEYS_DIR}/dispatcher/ssl/certs:/etc/ssl/certs
      - ${KEYS_DIR}/dispatcher/ssl/private:/etc/ssl/private
      - ${KEYS_DIR}/dispatcher/dh:/etc/nginx/dh

    environment:
      - NGINX_PORT=443
      - SSL_CERT_PATH=/etc/ssl/certs/nginx-selfsigned.crt
      - SSL_KEY_PATH=/etc/ssl/private/nginx-selfsigned.key
      - DHPARAM_PATH=/etc/nginx/dh/nginx-dhparam.pem

      - WEBFRONT_NODE_PORT=${WEBFRONT_NODE_PORT}
      - WEBFRONT_DEV_NODE_PORT=${WEBFRONT_DEV_NODE_PORT}

      - CHAT_API_NODE_PORT=${CHAT_API_NODE_PORT}
      - CHAT_API_BASEPATH=${CHAT_API_BASEPATH}

      - GPT_API_NODE_PORT=${GPT_API_NODE_PORT}
      - GPT_API_BASEPATH=${GPT_API_BASEPATH}

      - MONGO_ADMIN_PORT=${MONGO_ADMIN_PORT}
      - MONGO_ADMIN_BASEPATH=${MONGO_ADMIN_BASEPATH}

        SYNCTHING_ADMIN_HOST=${SYNCTHING_ADMIN_HOST}
      - SYNCTHING_ADMIN_BASEPATH=${SYNCTHING_ADMIN_BASEPATH}
      - SYNCTHING_ADMIN_PORT=${SYNCTHING_ADMIN_PORT}

    networks:
      - dispatcher

    ports:
      - "443:443"
      - "444:444"

  webfront:
    build: "./images/nodeapp"

    depends_on:
      mongo-server:
        condition: service_healthy

    entrypoint: npm run dev -- --host --port=${WEBFRONT_NODE_PORT}
    working_dir: /app
    volumes:
      - ${APPS_DIR}/webfront:/app

    environment:
      - NODE_PORT=${WEBFRONT_NODE_PORT}
      - DEV_NODE_PORT=${WEBFRONT_DEV_NODE_PORT}
      - NODE_TLS_REJECT_UNAUTHORIZED=0

      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - ORIGIN=${SITE_ORIGIN}

      - USER_ID=${WEBFRONT_INITIAL_USERNAME}
      - USER_PASSWORD=${WEBFRONT_INITIAL_PASSWORD}

      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_INITIAL_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITIAL_PASSWORD}

    networks:
      - dispatcher
      - node-mongo

  gpt-api:
    build: "./images/nodeapp"

    depends_on:
      mongo-server:
        condition: service_healthy

    entrypoint: npm run dev -- --host --port=${GPT_API_NODE_PORT}
    working_dir: /app
    volumes:
      - ${APPS_DIR}/gptapi:/app

    environment:
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_INITIAL_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITIAL_PASSWORD}
      - BASEPATH=${GPT_API_BASEPATH}

    networks:
      - dispatcher
      - node-mongo

  chat-api:
    build: "./images/nodeapp"

    depends_on:
      mongo-server:
        condition: service_healthy

    entrypoint: npm run dev -- --host --port=${CHAT_API_NODE_PORT}
    working_dir: /app
    volumes:
      - ${APPS_DIR}/chatapi:/app

    environment:
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USERNAME=${MONGO_INITIAL_USERNAME}
      - MONGO_PASSWORD=${MONGO_INITIAL_PASSWORD}

    networks:
      - dispatcher
      - node-mongo

  mongo-server:
    image: "mongo:4.4.8"

    entrypoint: docker-entrypoint.sh mongod --replSet rs0 --keyFile=/data/keyfiles/mongokey --port=${MONGO_PORT}

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITIAL_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITIAL_PASSWORD}

    volumes:
      - ${KEYS_DIR}/mongo:/data/keyfiles/
      - ${BACKUPS_DIR}/mongo:/data/backups/
      # - ${DATA_DIR}/mongo:/data/db

    networks:
      - node-mongo

    healthcheck:
      test: mongo --port ${MONGO_PORT} --quiet --eval 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 0s

  mongo-admin:
    image: "mongo-express:1.0.0-alpha.4"

    depends_on:
      mongo-server:
        condition: service_healthy

    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_INITIAL_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_INITIAL_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITIAL_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITIAL_PASSWORD}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_SITE_BASEURL=${MONGO_ADMIN_BASEPATH}
      - ME_CONFIG_MONGODB_SERVER=mongo-server

    networks:
      - dispatcher
      - node-mongo

networks:
  node-mongo: {}
  dispatcher: {}
