---
- name: Recreate file structure
  hosts: dev_server
  remote_user: root
  vars_files:
    - 00-vars.yml

  tasks:
    - name: Make directory structure
      become: true
      ansible.builtin.file:
        path: "{{ project_root }}/{{ item }}"
        state: "directory"
        mode: "775"
      with_items:
        - "run/"
        - "backups/mongo"
        - "data/mongo"
        - "experiments/" # --this is a root for repo

    - name: Clone a git repo with project
      become: true
      ansible.builtin.git:
        repo: https://github.com/unel/experiments.git
        dest: "{{ project_root }}/experiments"
        version: main
        force: true
