---
- name: Recreate file structure
  hosts: dev_server
  remote_user: root
  vars_files:
    - 00-vars.yml

  tasks:
    - name: Add secrets directories to project
      become: true
      ansible.builtin.file:
        path: "{{ project_root }}/{{ item }}"
        state: "directory"
        mode: "775"
      with_items:
        - "keyfiles/mongo"
        - "keyfiles/dispatcher/dh"
        - "keyfiles/dispatcher/ssl/certs"
        - "keyfiles/dispatcher/ssl/private"

    - name: Fill root secrets
      become: true
      ansible.builtin.template:
        src: "{{ secrets_dir }}/envs/root.env.template"
        dest: "{{ project_root }}/experiments/.env"
        mode: "400"

    - name: Fill secrets (env files)
      become: true
      ansible.builtin.copy:
        src: "{{ item.from }}"
        dest: "{{ item.to }}"
        mode: "400"
      with_items:
        - {
            from: "{{ secrets_dir }}/envs/webfront.env",
            to: "{{ project_root }}/experiments/apps/webfront/.env",
          }
        - {
            from: "{{ secrets_dir }}/envs/chatapi.env",
            to: "{{ project_root }}/experiments/apps/chatapi/.env",
          }
        - {
            from: "{{ secrets_dir }}/envs/gptapi.env",
            to: "{{ project_root }}/experiments/apps/gptapi/.env",
          }
        - {
            from: "{{ secrets_dir }}/envs/tg.env",
            to: "{{ project_root }}/experiments/apps/tg/.env",
          }
        - {
            from: "{{ secrets_dir }}/envs/openai.env",
            to: "{{ project_root }}/experiments/apps/openai/.env",
          }

    - name: Fill secrets (key files)
      become: true
      ansible.builtin.copy:
        src: "{{ item.from }}"
        dest: "{{ item.to }}"
        mode: "400"
      with_items:
        - {
            from: "{{ secrets_dir }}/keyfiles/mongo-key",
            to: "{{ project_root }}/keyfiles/mongo/mongokey",
          }
        - {
            from: "{{ secrets_dir }}/keyfiles/mongo-connection-config.yaml",
            to: "{{ project_root }}/keyfiles/mongo/config.yaml",
          }
        - {
            from: "{{ secrets_dir }}/keyfiles/dispatcher-selfsigned.crt",
            to: "{{ project_root }}/keyfiles/dispatcher/ssl/certs/nginx-selfsigned.crt",
          }
        - {
            from: "{{ secrets_dir }}/keyfiles/dispatcher-selfsigned.key",
            to: "{{ project_root }}/keyfiles/dispatcher/ssl/private/nginx-selfsigned.key",
          }
        - {
            from: "{{ secrets_dir }}/keyfiles/dispatcher-dhparam.pem",
            to: "{{ project_root }}/keyfiles/dispatcher/dh/nginx-dhparam.pem",
          }

    - name: Change access mode for mongokey
      become: true
      ansible.builtin.file:
        path: "{{ project_root }}/keyfiles/mongo/mongokey"
        owner: 999
        mode: "400"
