---

- name: deploy structure
  ansible.builtin.import_playbook: '01-deploy-experiments-structure.playbook.yml'

- name: run containers
  ansible.builtin.import_playbook: '02-run-containers.playbook.yml'
